'\" t
.\"
.TH ARNOLD 8 "17 November 2000"
.SH NAME "arnold"
.B 
.IR "a"nother 
.IR "r"idicolous 
.IR "n"ormalization 
.IR "o"r 
.IR "l"iquidation 
.IR "d"evice
.SH SYNOPSIS
.B arnold [opts] <dut> [opts] <testbench> [opts]
.SH DESCRIPTION
.LP
.B Arnold
is a tool that allows you to test programms automatically. 
Arnold sends values specified in the testbench to the device under test and compares 
the output against the expected value. 
.LP
.SS OPTIONS
.TP
.BI "-c, --continue"
.B causes arnold to continue testing the programm even if one test has failed
.TP
.BI "-w, --web"
.B causes arnold to use web-based statistics
.TP
.BI "-v, --version"
.B Print Arnolds version number and exit.
.TP
.BI "-h, --help"
.B Print a summary of the command-line usage of arnold and exit.
.TP
.BI "-m, --make-coffee-please"
.B Make some fresh coffee and exit.
.LP
.LP
.SH TESTBENCH
.LP
.B 
In the testbench you have to specify the tests that are performed on the device under test.
The specified input string is send to the program and its output is compared to the specified pattern.
The testbench consists of many standalone-tests like that one shown below. The reserved word "DUT" will 
automatically be replaced by the <dut> specified in the command line.
.LP
.SS TESTING MODES
.TP
.BI PARAM
.B The device under test is executed with the specified arguments.  
.TP
.BI INTERACT
.B In interactive mode, the device under test is started and Arnold waits for the specified pattern. 
After the appearance, Arnold sends the specified string to the device under test.
.SS EXAMPLE
.B 
test {
  TYPE=PARAM
  NAME=testname1
  COMMENT=my first test with parameters
  CMD {echo "hello world" | DUT parameters}
  EXPECT -i {this must appear in the output}
  # this is a comment
  
} 
.LP
.LP  
test {
  TYPE=INTERACT
  NAME=testname2
  COMMENT=my second interacting test 
  CMD {telnet www.myserver.com 80}
  WAITFOR -i {connect}
  SEND "GET /index.html"
  EXPECT -i {me@myserver.com}

} 
.LP
The reserved keywords TYPE, NAME, COMMENT, CMD, WAITFOR, SEND, EXPECT are 
.IR "case-insensitive", 
the keyword "test" must be in lower case.
.TP
.BI "TYPE"
.B Can be "param" or "interact". Chooses the type of the test.
.TP
.BI "NAME"
.B Specifies the name printed out while test is in progress. 
.TP
.BI "COMMENT"
.B Describes the test.
.TP
.BI "CMD"
.B Commandline to execute the device under test. May be in normal shell-syntax.
.TP
.BI "WAITFOR [-i]"
.B Used in interactive-mode. Arnold waits until the specified pattern matches the output. 
Use regular expressions to describe the pattern. The switch "-i" disables case-sensitivity (ignore case).
.TP
.BI "SEND"
.B Used in interactive-mode. The specified text is send to the waiting device under test.
.TP
.BI "EXPECT [-i]"
.B Describes the pattern (as a regular expression) that is expected. 
The switch "-i" disables case-sensitivity (ignore case).






.SH BUGS
.B many ;-)
.SH "AUTHOR"
Daniel Koenig <daniel@der-arnold.de>
.br
Gerrit Hesse <gerrit@der-arnold.de>
